### ISSUE TITLE
options containing hyphens unrecognized

### ISSUE THREAD

**Issue by AljoschaMeyer** [dthree/vorpal#10] opened 2015-10-08 14:07 UTC
Options containing a hyphen, e.g. `vorpal.command('t').option('a-b')` are not added to args.options when given in the cli.

May I ask why vorpal doesn't simply wrap commander for command-parsing? I love what vorpal does, but this seems like reinventing the wheel - unless there's an obvious factor I'm missing...

**Comment by dthree** [comment] 2015-10-08 16:07
Funny enough, I actually based the original code off commander. However, I needed it to do some things a little differently. For example, commander doesn't support multiple-worded commands, and this required a bit of refactor and deviation from commander's course. Vorpal also supports piped commands and will be supporting other bash logic such as `&&`, etc.

Does that clarify a bit? I'll definitely be fixing all of these points as soon as possible!

**Comment by eliperelman** [comment] 2015-12-03 00:36
+1

**Comment by paglias** [comment] 2016-02-06 21:15
Something that could be related to the same thing:

if you pass a literal argument value in quotes `command "-value"` it's not recognized as an argument but in this case as an option with name `value`

**Comment by da70** [comment] 2016-02-19 23:43
[ Accidentally wrote this in the PR instead of this ticket.  Moved it here. ]

Hi,

Just submitted a PR for this.  Yesterday I was trying to add a `--dry-run` option and noticed it wasn't passing through.  I debugged and found the cause and came up with various solutions, then found this open ticket.

The cause:

In `util.buildCommandArgs`, this line:
```Javascript
      var long = String(o.long || '').replace(/--no-/g, '').replace(/-/g, '');
```
...normalizes `o.long` to "dryrun", but when this option was first defined in `util.parseArgs`, it was normalized using `minimist` to "dry-run", so the match in `util.buildCommandArgs` here fails:
```Javascript
      exist = exist === undefined && parsedArgs[long] !== undefined ? parsedArgs[long] : exist;
```

In the PR I just submitted I opted for a simple, direct fix, changing `.replace(/-/g, '')` to `.replace(/^-*/g, '')` so that only leading dashes are replaced.  (I just now noticed I forgot to remove the `/g`, which is now superfluous).

The more bulletproof solution would be to use `parsedArgs` in both places, perhaps something like this:

```Javascript
function normalizeArg(str) {
      var obj = minimist([str]);
      var normalizedArg;

      for (var key in obj) {
        if (obj.hasOwnProperty(key)) {
          if (key !== '_') {
            normalizedArg = key;
            break;
          }
        }
      }

      return normalizedArg;
    };

...

      var long = normalizeArg(String(o.long || '').replace(/--no-/g, ''));
```

I did test this and it worked, but you can see it's a bit awkward due to the fact that `parseArgs`, like `minimist`, takes an array and returns an object with an added `_` element.  Also, it sounds like the option parsing is going to be refactored at some point.  If it's desired, though, I can submit a separate PR that uses this approach.

I just now noticed that Travis CI builds failed with the same error I've been getting on my machine on `gulp build`.  To run the tests and get them to pass on my machine I had to edit `dist/util.js` as well as `lib/util.js` (but only checked in the latter, obviously).  This bugfix should work once `gulp build` is working again.

Hope this helps.  It would be great to have the ability to use hyphenated options because there are a lot of standard ones out there already.

Thanks.  Am really liking working with Vorpal so far.

.david

**Closed** 2016-03-02 05:18 UTC
Labels: bug

**Comment by lafkpages** [comment] 2023-03-20 10:09
It says closed as completed but it's still not working?
