### ISSUE TITLE
Turn Off Session Functionality

### ISSUE THREAD

**Issue by ac360** [dthree/vorpal#156] opened 2016-06-29 16:07 UTC
How can we turn off the session functionality, or immediately exit after a single command?

**Comment by dthree** [comment] 2016-06-29 16:19
Use `vorpal.parse()`, and don't use `vorpal.show()`.

[This SO answer should help](http://stackoverflow.com/questions/33489201/is-it-possible-to-create-a-vorpal-application-which-the-commands-output-goes-di).

**Comment by ekryski** [comment] 2016-07-03 09:05
I can confirm this works. This is how I am doing it.

```js
    if (process.argv.length > 2) {
      app.parse(process.argv);
    }
    else {
      app.execSync('help');
      // You could also call vorpal.delimeter('custom:').show()
    }
```


@dthree you probably close this.

**Closed** 2016-07-06 16:13 UTC

**Comment by praxiq** [comment] 2016-11-12 04:20
Maybe something has changed, but this does *not* work for me. Calling "parse" parses one command, then stays in the CLI, even without a "show." 

The code in the SO answer works for me, only because it forgets to call the callback at the end of the command! However, if I type any other command as an argument, it stays in the CLI after parse() completes.
