### ISSUE TITLE
Reference Error: ui is not defined

### ISSUE THREAD

**Issue by shayne** [dthree/vorpal#96] opened 2016-02-09 21:27 UTC
As of vorpal 1.8.8 I'm getting the following when issuing `vorpal.ui.redraw.clear(); vorpal.ui.redraw.done()`

```
Unhandled rejection ReferenceError: ui is not defined
    at Function.UI.redraw.clear (/Users/sweeney/Code/vorpal-trello/node_modules/vorpal/dist/ui.js:628:10)
    at _callee2$ (fetcher.js:27:22)
    at tryCatch (/Users/sweeney/Code/vorpal-trello/node_modules/babel-regenerator-runtime/runtime.js:61:40)
```

**Comment by scotthovestadt** [comment] 2016-02-09 21:56
Looking into it.

**Comment by dthree** [comment] 2016-02-09 21:58
Thanks.

**Comment by scotthovestadt** [comment] 2016-02-09 21:59
It looks like the function is ````ui.redraw.clear````and ````ui.redraw.done````.

@dthree Confirm that's intended?

**Comment by dthree** [comment] 2016-02-09 21:59
yeah that's weird. What's calling that?

**Comment by scotthovestadt** [comment] 2016-02-09 22:04
The issue is that those methods are on ````UI.redraw.clear```` and ````UI.redraw.done````, not actually on the UI class. Since the UI is a singleton we can inject the reference to it but it's just weird design that wasn't caught when we moved to Babel. I'm working on it, seeing if it's possible to put together a test case.

**Comment by dthree** [comment] 2016-02-09 22:05
? Not sure what moving to Babel does to this?

**Comment by scotthovestadt** [comment] 2016-02-09 22:08
@dthree It's because UI wasn't a ````class```` before, it was just an object, so the redraw function is a little weird. I think I've submitted a fix (please review). I'd like to get a test case for this type of thing too.

**Comment by dthree** [comment] 2016-02-09 22:11
Okay - looks okay. Could you look at this though:

https://github.com/dthree/vorpal/blob/e96e37daf2b8886155f219d83639a013a1a1f314/lib/ui.js#L569

UI already has some... interesting functionality in that it has to extend global for a single instance. This is really important, so I want to make sure these changes don't mess with that.

**Comment by scotthovestadt** [comment] 2016-02-09 22:14
Yeah, I looked at this earlier, I think it's basically a singleton. It's interesting design but I don't see an issue with it.

**Comment by dthree** [comment] 2016-02-09 22:15
Okay. Go ahead and merge, and I'll publish. :+1:

**Comment by scotthovestadt** [comment] 2016-02-09 22:16
Should be ready for publish but if @shayne can verify it solves his issue that'd be ideal.

**Comment by dthree** [comment] 2016-02-09 22:20
Okay we'll wait up a bit for him. I think I stumbled into this as well yesterday but didn't have time to look into it, so I'll check it out on my pjt.

**Comment by dthree** [comment] 2016-02-09 22:48
Okay I pretty thoroughly tested it. Published, but want to wait for @shayne before closing this issue.

Thanks for your help @scotthovestadt - I'm happy Vorpal has a bus factor of 2 now :smiley:

**Comment by shayne** [comment] 2016-02-09 22:57
This works great. Amazing speed. :trophy:

**Comment by dthree** [comment] 2016-02-09 22:57
Great!

**Closed by dthree** 2016-02-09 22:57 UTC
